# Generated by Django 6.1 on 2026-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine_type', models.CharField(choices=[('L', 'L (faible qualité)'), ('M', 'M (qualité moyenne)'), ('H', 'H (haute qualité)')], default='M', max_length=1)),
                ('air_temperature', models.FloatField(help_text='Air temperature [K]')),
                ('process_temperature', models.FloatField(help_text='Process temperature [K]')),
                ('rotational_speed', models.FloatField(help_text='Rotational speed [rpm]')),
                ('torque', models.FloatField(help_text='Torque [Nm]')),
                ('tool_wear', models.FloatField(help_text='Tool wear [min]')),
                ('reconstruction_error', models.FloatField()),
                ('threshold_used', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('top_variable', models.CharField(blank=True, max_length=64)),
                ('top_variable_error', models.FloatField(default=0.0)),
                ('feature_errors', models.JSONField(blank=True, default=list, help_text='Liste [[nom_variable, erreur], ...] triée par contribution décroissante')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
